import React,{useEffect,useState} from "react";
import {api} from "./api";

const empty={firstName:"",lastName:"",phoneNumber:"",email:"",password:""};
function Auth({onLogin}){
 const [mode,setMode]=useState("login"),[form,setForm]=useState(empty),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setError("");setLoading(true);try{const d=await api("/auth/"+mode,{method:"POST",body:JSON.stringify(form)});localStorage.setItem("token",d.data.token);onLogin();}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <main className="auth"><section className="card auth-card"><p className="eyebrow">PHEGON BANK</p><h1>{mode==="login"?"Welcome back":"Open your account"}</h1><p className="muted">{mode==="login"?"Secure access to your accounts and transactions.":"Create a savings account in seconds."}</p>
 <form onSubmit={submit}>{mode==="register"&&<><input placeholder="First name" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="Last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><input placeholder="Phone number" value={form.phoneNumber} onChange={e=>setForm({...form,phoneNumber:e.target.value})}/></>}<input type="email" placeholder="Email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" required minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?"Please wait…":mode==="login"?"Login":"Create account"}</button></form>
 <button className="link" onClick={()=>{setMode(mode==="login"?"register":"login");setError("")}}>{mode==="login"?"New here? Create an account":"Already registered? Login"}</button></section></main>;
}
function Dashboard({logout}){
 const [user,setUser]=useState(null),[accounts,setAccounts]=useState([]),[selected,setSelected]=useState(null),[tx,setTx]=useState([]),[error,setError]=useState(""),[amount,setAmount]=useState(""),[destination,setDestination]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [u,a]=await Promise.all([api("/auth/me"),api("/accounts")]);setUser(u.data);setAccounts(a.data);if(a.data.length&&!selected)setSelected(a.data[0]);}catch(e){if(/401|403/i.test(e.message))logout();else setError(e.message)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(selected)api("/transactions/"+selected.accountNumber).then(d=>setTx(d.data)).catch(e=>setError(e.message))},[selected]);
 const transaction=async type=>{if(!selected)return;setBusy(true);setError("");try{await api("/transactions",{method:"POST",body:JSON.stringify({transactionType:type,amount:Number(amount),accountNumber:selected.accountNumber,destinationAccountNumber:type==="TRANSFER"?destination:undefined,description:type+" via web app"})});setAmount("");setDestination("");await load();}catch(e){setError(e.message)}finally{setBusy(false)}};
 const createAccount=async()=>{try{await api("/accounts?accountType=SAVINGS&currency="+(selected?.currency||"USD"),{method:"POST"});await load()}catch(e){setError(e.message)}};
 return <main className="app"><nav><div><span className="logo">P</span><strong>Phegon Bank</strong></div><button className="ghost" onClick={logout}>Logout</button></nav><section className="content"><header><div><p className="eyebrow">DASHBOARD</p><h1>Hello, {user?.firstName||"Customer"}</h1></div><button onClick={createAccount}>+ New account</button></header>{error&&<div className="error">{error}</div>}<div className="accounts">{accounts.map(a=><button key={a.id} className={"account "+(selected?.id===a.id?"active":"")} onClick={()=>setSelected(a)}><span>{a.accountType} · {a.currency}</span><b>{Number(a.balance).toFixed(2)}</b><small>{a.accountNumber}</small></button>)}</div>{selected&&<section className="grid"><div className="card"><h2>Move money</h2><input type="number" min="0.01" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Destination account for transfer" value={destination} onChange={e=>setDestination(e.target.value)}/><div className="actions"><button disabled={busy} onClick={()=>transaction("DEPOSIT")}>Deposit</button><button disabled={busy} onClick={()=>transaction("WITHDRAWAL")}>Withdraw</button><button disabled={busy} onClick={()=>transaction("TRANSFER")}>Transfer</button></div></div><div className="card"><h2>Recent transactions</h2>{tx.length===0?<p className="muted">No transactions yet.</p>:tx.slice(0,10).map(t=><div className="tx" key={t.id}><div><b>{t.transactionType}</b><small>{new Date(t.transactionDate).toLocaleString()}</small></div><strong>{Number(t.amount).toFixed(2)}</strong></div>)}</div></section>}</section></main>;
}
export default function App(){const [logged,setLogged]=useState(!!localStorage.getItem("token"));const logout=()=>{localStorage.removeItem("token");setLogged(false)};return logged?<Dashboard logout={logout}/>:<Auth onLogin={()=>setLogged(true)}/>;}
